"use client"
import React from "react"

import { ThemeProvider } from "next-themes"
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/toaster"
import { Toaster as Sonner } from "@/components/ui/sonner"
// import type { Metadata } from "next"
import "./app.css"
import "./globals.css"
import { Navbar } from "@/components/Navbar"
import { Footer } from "@/components/Footer"
import { CreateMarketProvider } from "@/context/CreateMarketContext"

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
					<CreateMarketProvider>
						<TooltipProvider>
							<Toaster />
							<Sonner />
							<Navbar />
							{children}
							<Footer />
						</TooltipProvider>
					</CreateMarketProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
